storyabout/main/urls.py
from django.urls import path
from . import views

# Application name "main"
app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index')
]

storyabout/storyabout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('registrationlogin/', include('registrationlogin.urls', namespace='registrationlogin')),
    path('story/', include('story.urls', namespace='story')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storyabout/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('edit/', views.edit_profile_view, name='edit'),
    path('delete/', views.delete_profile_view, name='delete'),
]

storyabout/userprofile/models.py
from django.db import models
from django.contrib.auth import get_user_model
from story.models import Story

User = get_user_model()

# Model to track the user's reading progress for each story
class UserStoryProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.story.title} - Read: {self.read}"

storyabout/userprofile/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

User = get_user_model()

# User profile edit form
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']
        labels = {
            'first_name':'First Name',
            'last_name':'Last Name',
        }
    
    # Username field verification
    def clean_username(self):
        username = self.cleaned_data.get('username', '')

        if len(username) < 3:
            raise ValidationError("Username must contain at least 3 characters.")
        elif len(username) > 20:
            raise ValidationError("Username must contain less then 20 characters.")
        if not any(char.isalpha() for char in username):
            raise ValidationError("Username must contain at least one letter.")
        return username
    
    # First name field verification
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name', '')

        if not first_name.isalpha():
            raise ValidationError("First name should contain only letters.")
        if not first_name[0].isupper():
            raise ValidationError("First name should start with a capital letter.")
        if len(first_name) < 3:
            raise ValidationError("First name must contain at least 3 characters.")
        elif len(first_name) > 20:
            raise ValidationError("First name must contain less then 20 characters.")
        return first_name
    
    # Last name field verification
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name', '')
        
        if not last_name.isalpha():
            raise ValidationError("Last name should contain only letters.")
        if not last_name[0].isupper():
            raise ValidationError("Last name should start with a capital letter.")
        if len(last_name) < 3:
            raise ValidationError("First name must contain at least 3 characters.")
        elif len(last_name) > 20:
            raise ValidationError("First name must contain less then 20 characters.")
        return last_name

storyabout/userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .models import UserStoryProgress
from .forms import CustomUserChangeForm

# View user profilewith necessary and not secret data
@login_required
def profile_view(request):
    user_progress = UserStoryProgress.objects.filter(user=request.user, read=True)
    data = {
        'user_progress': user_progress,
        'email': request.user.email,
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
    }
    return render(request, 'userprofile/profile.html', data)


# View to edit user profile (edit firstname, lastname, username)
@login_required
def edit_profile_view(request):
    
    # Bind the current user's data to the form
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():  # Validate form input
            form.save()  # Save form
            return redirect('userprofile:profile')
    else:
        # Pre-fill the form with the current user's data
        form = CustomUserChangeForm(instance=request.user)

    return render(request, 'userprofile/edit.html', {'form': form})


# View to delete user profile
@login_required
def delete_profile_view(request):
    user = request.user
    user.delete() # Delete user
    logout(request) # Logout from current user 
    return redirect('registrationlogin:login') # Redirect to login in view



storyabout/userprofile/templates/userprofile/edit.html
{% extends 'story/layout.html' %}

{% block content %}
<div class="prof back__layer">
  {% if form.errors %}
  <div class="error-messages">
      <ul>
          {% for field, errors in form.errors.items %}
              {% for error in errors %}
                  <li><strong>{{ field|capfirst }}</strong>: {{ error }}</li>
              {% endfor %}
          {% endfor %}
      </ul>
  </div>
  {% endif %}
    <div class="container__form d-flex justify-content-center align-items-center">
        <div class="div__form">
            <h2>Edit Profile</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="my-3 d-flex align-items-center flex-column">
                  <h3 class="my-0">Username</h3>
                  <div class="px-3">
                    {{ form.username }}
                  </div>
                </div>
                <div class="my-3 d-flex align-items-center flex-column">
                  <h3 class="my-0">First Name</h3>
                  <div class="px-3">
                    {{ form.first_name }}
                  </div>
                </div>
                <div class="my-3 d-flex align-items-center flex-column">
                  <h3 class="my-0">Last Name</h3>
                  <div class="px-3">
                    {{ form.last_name }}
                  </div>
                </div>
                <button type="submit" class="btn btn-outline-warning">Edit</button>
            </form>
        </div>
      </div>
</div>

<!-- Additional styles -->
<style media="screen">
  h2:hover{
    color: #ff9a00
  }
  h3{
    width: auto;
  }
  p:hover{
    color: #ff9a00
  }
</style>

{% endblock %}

storyabout/userprofile/templates/userprofile/profile.html
{% extends 'story/layout.html' %}

{% block content %}
<div class="prof back__layer">
  <aside class="control_menu">
    <div class="text-start">
      <h2 class="my-5">{{ request.user.username }}'s Profile</h2>
      <p>Email: {{ email }}</p>
      <p>First Name: {{ first_name }}</p>
      <p>Last Name: {{ last_name }}</p>
      <h3 class="my-5">Stories You've Read:</h3>
          {% for progress in user_progress %}
          <p>
            <span>{{ progress.story.title }}</span>
            <span class="checkmark">✔</span>
          </p>
          {% empty %}
              <p>No stories read yet.</p>
          {% endfor %}
    </div>
    <div class="text-start">
      <a class="btn btn-outline-dark"  href="{% url 'userprofile:edit' %}">Edit...</a>
      <a class="btn btn-outline-danger" href="{% url 'userprofile:delete' %}">Delete...</a>
    </div>
  </aside>
  <div class="p-5">
    <h2 >In literature, as in life, it is worth remembering </h2>
    <h2 class="vertical__title" style="font-size: 60px;">one rule:</h2>
    <h2>a person will repent a thousand times for having said a lot, but never for having said little.</h2>
  </div>
</div>

<!-- Additional styles -->
<style media="screen">
  h2:hover{
    color: #ff9a00
  }
  h3{
    width: auto;
  }
  p:hover{
    color: #ff9a00
  }
</style>

{% endblock %}