storyabout/main/urls.py
from django.urls import path
from . import views

# Application name "main"
app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index')
]

storyabout/registrationlogin/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

# Application name
app_name = 'registrationlogin'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('register/', views.RegisterUser.as_view(), name = 'register'),
]

storyabout/story/urls.py
from django.urls import path
from . import views

app_name = 'story'

urlpatterns = [
    path('create-story/', views.create_story, name='create_story'),
    path('add-frame/<int:story_id>/', views.add_frame, name='add_frame'),
    path('delete-story/<int:story_id>/', views.delete_story, name='delete_story'),
    path('story/<int:story_id>/', views.story_detail, name='story_details'),
    path('stories/', views.stories, name='stories'),
    path('mark-as-read/<int:story_id>/', views.mark_as_read, name='mark_as_read'),
    path('edit_frame/<int:story_id>/<int:frame_id>/', views.edit_frame, name='edit_frame'),
]

storyabout/storyabout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('registrationlogin/', include('registrationlogin.urls', namespace='registrationlogin')),
    path('story/', include('story.urls', namespace='story')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storyabout/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('edit/', views.edit_profile_view, name='edit'),
    path('delete/', views.delete_profile_view, name='delete'),
]

storyabout/story/models.py
from django.db import models

# Story model
class Story(models.Model):
    title = models.CharField('Title', max_length=50)
    author = models.CharField('Author', max_length=50)
    background_image = models.ImageField('Background Image', upload_to='backgrounds/', blank=False, null=True)

    def __str__(self):
        return self.title

# Story frame model
class StoryFrame(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='frames')
    chapter = models.IntegerField(null=True, blank=True)
    image = models.ImageField(upload_to='slides/', blank=True, null=True)
    paragraph = models.TextField(blank=True, null=True)
    position = models.CharField('Position', max_length=50, blank=True, null=True)  # Ensure position field exists

    def __str__(self):
        return f"Frame {self.chapter} for {self.story.title}"

storyabout/story/forms.py
import re
from django import forms
from .models import Story, StoryFrame
from django.forms import TextInput, Textarea, ClearableFileInput, NumberInput
from django.core.exceptions import ValidationError

# Story form
class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = [
            'title', 'author', 'background_image',
        ]

        widgets = {
            "background_image": ClearableFileInput(attrs={
                'class': 'form-control',
            }),
            "title": TextInput(attrs={
                'class': 'form-control',
            }),
            "author": TextInput(attrs={
                'class': 'form-control',
            }),
        }
        
    # Title field verification
    def clean_title(self):
        title = self.cleaned_data.get('title', '')

        if len(title) < 3:
            raise ValidationError("Title must contain at least 3 characters.")
        elif len(title) > 30:
            raise ValidationError("Title must contain less then 30 characters.")
        if not title[0].isupper():
            raise ValidationError("Title should start with a capital letter.")
        if not any(char.isalpha() for char in title):
            raise ValidationError("Title must contain at least one letter.")
        if not re.match(r"^[A-Za-z0-9\s.,?!']+$", title):
            raise ValidationError("Title contains invalid characters. Use only letters, numbers, spaces, and basic punctuation.")
        return title

    # Author field verification
    def clean_author(self):
        author = self.cleaned_data.get('author', '')

        if not author[0].isupper():
            raise ValidationError("Author should start with a capital letter.")
        if len(author) < 3:
            raise ValidationError("Author must contain at least 3 characters.")
        elif len(author) > 40:
            raise ValidationError("Author must contain less then 40 characters.")
        if not re.match(r"^[A-Za-z0-9\s.,?!']+$", author):
            raise ValidationError("Author contains invalid characters. Use only letters, numbers, spaces, and basic punctuation.")
        return author

# Story frame form
class StoryFrameForm(forms.ModelForm):
    class Meta:
        model = StoryFrame
        fields = ['chapter', 'paragraph', 'image', 'position']

        widgets = {
            "chapter": NumberInput(attrs={
                'class': 'form-control',
            }),
            "image": ClearableFileInput(attrs={
                'class': 'form-control',
            }),
            "paragraph": Textarea(attrs={
                'class': 'form-control',
                'rows': 20,
            }),
            "position": TextInput(attrs={
                'class': 'form-control',
            }),
        }
    # Paragraph field verification
    def clean_paragraph(self):
        paragraph = self.cleaned_data.get('paragraph', '')
        if paragraph:
            stripped_paragraph = paragraph.replace(" ", "")
            
            num_letters = sum(c.isalpha() for c in stripped_paragraph)
            num_numbers = sum(c.isdigit() for c in stripped_paragraph)
            if len(paragraph) < 80:
                raise ValidationError("Title must contain at least 20 characters.")
            elif len(paragraph) > 2000:
                raise ValidationError("Title must contain less then 30 characters.")
            if num_letters <= num_numbers:
                raise ValidationError("The paragraph must contain more letters than numbers.")
            # if not re.match(r"^[A-Za-z0-9\s.,?!']+$", paragraph):
            #     raise ValidationError("The paragraph contains invalid characters. Use only letters, numbers, spaces, and basic punctuation.")
            if not paragraph[0].isupper():
                raise ValidationError("The paragraph should start with a capital letter.")
        return paragraph

    # Custom position choice field with options
    POSITION_CHOICES = [
        ('left', 'Left'),
        ('center', 'Center'),
        ('right', 'Right'),
    ]
    position = forms.ChoiceField(choices=POSITION_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
        'placeholder': 'Position',
    }))

storyabout/story/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms import modelformset_factory
from .forms import StoryForm, StoryFrameForm
from .models import Story, StoryFrame
from userprofile.models import UserStoryProgress
import os
from django.conf import settings


# Check if user is an admin (superuser or staff)
def admin_required(user):
    return user.is_staff or user.is_superuser



# View to create a new story
@login_required
@user_passes_test(admin_required)
def create_story(request):
    if request.method == 'POST':
        form = StoryForm(request.POST, request.FILES)
        if form.is_valid():
            story = form.save() # Save valid form
            return redirect('story:add_frame', story_id=story.id)  # Redirect to add frames after creating the story
    else:
        form = StoryForm()
    return render(request, 'story/create_story.html', {'form': form})



# View to add a frame (chapter) to a story
@login_required
@user_passes_test(admin_required)
def add_frame(request, story_id):
    # Retrieve the story by its ID
    story = get_object_or_404(Story, id=story_id)
    if request.method == 'POST':
        form = StoryFrameForm(request.POST, request.FILES)
        if form.is_valid():
            frame = form.save(commit=False)
            frame.story = story  # Associate the frame with the story
            frame.save() # Save story
            return redirect('story:story_details', story_id=story.id)  # Redirect to story detail after adding the frame
    else:
        form = StoryFrameForm()
    return render(request, 'story/add_frame.html', {'form': form, 'story': story})


# View to edit a frame (chapter) to a story
@login_required
@user_passes_test(admin_required)
def edit_frame(request, story_id, frame_id):
    # Retrieve the story by its ID
    story = get_object_or_404(Story, id=story_id)
    frame = get_object_or_404(StoryFrame, id=frame_id, story=story)

    if request.method == 'POST':
        form = StoryFrameForm(request.POST, request.FILES, instance=frame)
        if form.is_valid():
            form.save()
            return redirect('story:story_details', story_id=story.id)
    else:
        form = StoryFrameForm(instance=frame)

    return render(request, 'story/edit_frame.html', {'form': form, 'story': story})


# View to delete a story
def delete_story(request, story_id):
    # Retrieve the story by its ID
    story = get_object_or_404(Story, id=story_id)

    # Delete associated images from StoryFrame
    for frame in story.frames.all():
        if frame.image:
            file_path = os.path.join(settings.MEDIA_ROOT, frame.image.name)
            if os.path.isfile(file_path):
                os.remove(file_path)

    # Check and delete the background image of the story
    if story.background_image:
        background_file_path = os.path.join(settings.MEDIA_ROOT, story.background_image.name)
        if os.path.isfile(background_file_path):
            os.remove(background_file_path)

    story.delete()

    # Retrieve all stories to render the updated list
    stories = Story.objects.all()
    return render(request, 'story/stories.html', {'stories': stories})



# View to open a story details (the view with frames of current story)
@login_required
def story_detail(request, story_id):
    # Retrieve the story by its ID
    story = get_object_or_404(Story, id=story_id)

    # Get all the associated frames (chapters) for this story
    frames = story.frames.all()  # Collect all story frames of current story

    progress = UserStoryProgress.objects.filter(user=request.user, story=story).first()

    user_has_read_story = progress.read if progress else False

    # Pass the story and its frames to the template
    return render(request, 'story/story_details.html', {'story': story, 'frames': frames, 'user_has_read_story': user_has_read_story})



# View to mark the story as completed for current user
@login_required
def mark_as_read(request, story_id):
    # Retrieve the story by its ID
    story = get_object_or_404(Story, id=story_id)
    progress, created = UserStoryProgress.objects.get_or_create(user=request.user, story=story)

    # Toggle the read status
    progress.read = not progress.read
    progress.save()

    return redirect('story:stories')

# View to go back to all stories
@login_required
def stories(request):
    stories = Story.objects.all()

    return render(request, 'story/stories.html', {'stories': stories})

storyabout/story/templates/story/add_frame.html
{% extends 'story/layout.html' %}

{% block content %}
  <div class="back__layer">
    <!-- Errors notifications -->
    {% if form.errors %}
      <div class="error-messages">
        <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>
                <strong>{{ field|capfirst }}</strong>: {{ error }}
              </li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}

    <!-- Add frame form -->
    <div class="container__form d-flex justify-content-center align-items-center">
      <div class="div__form">
        <h2>Add a Frame to {{ story.title }}</h2>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="my-3 d-flex align-items-center">
            <h3 class="my-0">Chapter</h3>
            <div class="px-3">{{ form.chapter }}</div>
          </div>
          <div class="d-flex align-items-center">
            <input class="form-check-input m-0" type="radio" id="paragraph" name="background" value="color" onclick="toggleFrameTypeVisibility(this)" />
            <h4 class="mx-3 my-0" for="color">Paragraph</h4>
            <input class="form-check-input m-0" type="radio" id="image" name="background" value="color" onclick="toggleFrameTypeVisibility(this)" />
            <h4 class="mx-3 my-0" for="color">Image</h4>
          </div>

          <div id="frame__paragraph" class="d-none my-3">
            <div class="d-flex">
              <h1 class="vertical__title mx-4">Paragraph</h1>
              {{ form.paragraph }}
            </div>
          </div>
          <div id="frame__image" class="d-none my-3">
            <h2 class="draft__title">Image</h2>
            {{ form.image }}
          </div>
          <div class="my-3">{{ form.position }}</div>

          <button type="submit" class="btn btn-outline-warning">Add Frame</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

storyabout/story/templates/story/create_story.html
{% extends 'story/layout.html' %}

{% block content %}
  <div class="back__layer">
    <!-- Errors notifications -->
    {% if form.errors %}
      <div class="error-messages">
        <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>
                <strong>{{ field|capfirst }}</strong>: {{ error }}
              </li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}
     <!-- Create story form -->
    <div class="container__form d-flex justify-content-center align-items-center">
      <div class="div__form">
        <h2>Add new story</h2>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="my-3 d-flex align-items-center">
            <h3 class="my-0">Title</h3>
            <div class="px-3">{{ form.title }}</div>
          </div>
          <div class="my-3 d-flex align-items-center">
            <h3 class="my-0">Author</h3>
            <div class="px-3">{{ form.author }}</div>
          </div>
          <div class="my-3 d-flex align-items-center">
            <h3 class="my-0 draft__title">Book Cover</h3>
            <div class="px-3">{{ form.background_image }}</div>
          </div>
          <button type="submit" class="btn btn-outline-warning">Create Story</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

storyabout/story/templates/story/edit_frame.html
{% extends 'story/layout.html' %}

{% block content %}
  <div class="stories d-flex justify-content-center">
    <!-- Errors notifications -->
    {% if form.errors %}
      <div class="error-messages">
        <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>
                <strong>{{ field|capfirst }}</strong>: {{ error }}
              </li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}
    <!-- Edit frame form -->
    <div class="w-50">
      <div class="div__form">
        <h2 class="text-center">Edit Frame for Story: {{ story.title }}</h2>
        <form method="POST" enctype="multipart/form-data" class="p-4">
          {% csrf_token %}

          <!-- Chapter -->
          <div class="form-group mb-3">
            <label for="id_chapter">Chapter:</label>
            {{ form.chapter }}
          </div>
          {% if form.paragraph.value %}
            <div id="frame__paragraph" class="my-3">
              <div class="d-flex">
                <h1 class="vertical__title mx-4">Paragraph</h1>
                {{ form.paragraph }}
              </div>
            </div>
          {% else %}
            <div id="frame__image" class="my-3">
              <h2 class="draft__title">Image</h2>
              <input type="file" name="{{ form.image.name }}" />
            </div>
          {% endif %}
          <div class="my-3">{{ form.position }}</div>
          <!-- Submit Button -->
          <button type="submit" class="btn btn-primary">Save Frame</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

storyabout/story/templates/story/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Story About</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:ital,wght@0,400;0,700;1,300&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'story/css/main.css' %}" />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>
    <script src="{% static 'story/js/app.js' %}" defer></script>
  </head>
  <body>
    <header class="header" id="header">
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark mx-3">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:index' %}">STORY ABOUT ...</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'story:stories' %}">STORIES</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'story:create_story' %}">CREATE STORY</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:profile' %}">PROFILE</a>
              </li>

              <li class="nav-item">
                <form action="{% url 'registrationlogin:logout' %}" method="post">
                  {% csrf_token %}
                  <button class="nav-link" type="submit">LOGOUT</button>
                  </form>
              </li>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    {% block content %}

    {% endblock %}
  </body>
</html>

storyabout/story/templates/story/stories.html
{% extends 'story/layout.html' %}

{% block content %}
 <!-- Stories -->
  <div class="stories">
    {% if stories %}
      {% for story in stories %}
        <div class="story__item d-flex justify-content-center align-items-center my-5 py-5">
          <div class="story__container">
            <a href="{% url 'story:story_details' story.id %}">
              <div class="story__image">
                <img src="{{ story.background_image.url }}" alt="" />
              </div>
              <div class="story__content">
                <div>
                  <h2 class="story__text">{{ story.title }}</h2>
                  <h3 class="story__text">{{ story.author }}</h3>
                </div>
              </div>
            </a>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}

storyabout/story/templates/story/story_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Story About</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:ital,wght@0,400;0,700;1,300&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'story/css/main.css' %}" />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>
    <script src="{% static 'story/js/app.js' %}" defer></script>

    <style media="screen">
      body {
        height: var(--depth);
      }
    </style>
  </head>
  <body>
     <!-- Story frames -->
    <div class="mycontainer">
      <section class="gallery">
        {% if frames %}
          {% for frame in frames %}
            {% if frame.image %}
              <div class="frame {% if forloop.counter|divisibleby:3 %}frame_bg{% endif %}">
                {% if request.user.is_staff or request.user.is_superuser %}
                  <a href="{% url 'story:edit_frame' story.id frame.id %}">
                    <div class="frame__content">
                      <div class="frame-media frame-media_{{ frame.position }}" style="background-image: url({{ frame.image.url }})"></div>
                    </div>
                  </a>
                {% else %}
                  <div class="frame__content">
                    <div class="frame-media frame-media_{{ frame.position }}" style="background-image: url({{ frame.image.url }})"></div>
                  </div>
                {% endif %}
              </div>
            {% endif %}
            {% if frame.paragraph %}
              <div class="frame {% if forloop.counter|divisibleby:3 %}frame_bg{% endif %}">
                {% if request.user.is_staff or request.user.is_superuser %}
                  <a href="{% url 'story:edit_frame' story.id frame.id %}">
                    <div class="frame__content text-{{ frame.position }}">
                      <h3>Chapter {{ frame.chapter }}</h3>
                      <p>{{ frame.paragraph }}</p>
                    </div>
                  </a>
                {% else %}
                  <div class="frame__content text-{{ frame.position }}">
                    <h3>Chapter {{ frame.chapter }}</h3>
                    <p>{{ frame.paragraph }}</p>
                  </div>
                {% endif %}
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}
        <div class="frame">
          <div class="frame__content text-center">
            <form method="post" action="{% url 'story:mark_as_read' story.id %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-dark py-3">
                You have reached the end of a wonderful story about... <br />

                {% if user_has_read_story %}
                  Mark as Unread
                {% else %}
                  Mark as Read
                {% endif %}
              </button>
            </form>
          </div>
        </div>
      </section>
    </div>
    <!-- Administration button which are available only for administrators -->
    {% if request.user.is_staff or request.user.is_superuser %}
      <a class="addframe__button btn btn-outline-dark" href="{% url 'story:add_frame' story.id %}">Frame...</a>
      <a class="delete__story__button btn btn-outline-dark" href="{% url 'story:delete_story' story.id %}">Delete Story...</a>
    {% endif %}
    <a class="stories__button btn btn-outline-dark" href="{% url 'story:stories' %}">Stories...</a>
  </body>
</html>