storyabout/main/urls.py
from django.urls import path
from . import views

# Application name "main"
app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index')
]

storyabout/registrationlogin/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

# Application name
app_name = 'registrationlogin'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('register/', views.RegisterUser.as_view(), name = 'register'),
]

storyabout/storyabout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('registrationlogin/', include('registrationlogin.urls', namespace='registrationlogin')),
    path('story/', include('story.urls', namespace='story')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storyabout/registrationlogin/models.py
from django.db import models

storyabout/registrationlogin/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

# Login user form
class LoginUserForm(AuthenticationForm):
    class Meta:
        model = get_user_model # Authenticate user form
        fields = ['username', 'password'] # Included fields to form


# Register user form
class RegisterUserForm(UserCreationForm):
    # Form fields
    username = forms.CharField(label = "User Name")
    password1 = forms.CharField(label = "Password", widget=forms.PasswordInput())
    password2 = forms.CharField(label = "Confirm password", widget=forms.PasswordInput())
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email':'E-mail',
            'first_name':'First Name',
            'last_name':'Last Name',
        }

    # Email verification
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email = email).exists():
            raise forms.ValidationError("User with that email exist.")
        return email
    
    # Username verification
    def clean_username(self):
        username = self.cleaned_data.get('username', '')

        if len(username) < 3:
            raise ValidationError("Username must contain at least 3 characters.")
        elif len(username) > 20:
            raise ValidationError("Username must contain less then 20 characters.")
        if not any(char.isalpha() for char in username):
            raise ValidationError("Username must contain at least one letter.")
        return username

    # First name verification
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name', '')

        if not first_name.isalpha():
            raise ValidationError("First name should contain only letters.")
        if not first_name[0].isupper():
            raise ValidationError("First name should start with a capital letter.")
        if len(first_name) < 3:
            raise ValidationError("First name must contain at least 3 characters.")
        elif len(first_name) > 20:
            raise ValidationError("First name must contain less then 20 characters.")
        return first_name

    # Last name verification
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name', '')
        
        if not last_name.isalpha():
            raise ValidationError("Last name should contain only letters.")
        if not last_name[0].isupper():
            raise ValidationError("Last name should start with a capital letter.")
        if len(last_name) < 3:
            raise ValidationError("First name must contain at least 3 characters.")
        elif len(last_name) > 20:
            raise ValidationError("First name must contain less then 20 characters.")
        return last_name

storyabout/registrationlogin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import CreateView
from .forms import LoginUserForm, RegisterUserForm
from django.urls import reverse_lazy

# Login in view
class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'registrationlogin/login.html'
    extra_context = {'title': 'Authorization'}
    # Dispatch method use to process requsest
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('story:stories')
        return super().dispatch(request, *args, **kwargs)

    def form_invalid(self, form):
        # Add a custom error message or log
        return self.render_to_response(self.get_context_data(form=form))

# Register view
class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'registrationlogin/registration.html'
    extra_context = {'title': 'Registration'}
    success_url = reverse_lazy('registrationlogin:login')
    # Dispatch method use to process requsest
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('story:stories')
        return super().dispatch(request, *args, **kwargs)

    def form_invalid(self, form):
        # Add a custom error message or log
        return self.render_to_response(self.get_context_data(form=form))


storyabout/registrationlogin/templates/registrationlogin/login.html
{% extends 'story/layout.html' %}

{% block content %}
  <div class="back__layer">
    <!-- Errors notifications -->
    {% if form.errors %}
      <div class="error-messages">
        <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>
                <strong>{{ field|capfirst }}</strong>: {{ error }}
              </li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}

    <!-- Login form -->
    <div class="container__form d-flex justify-content-center align-items-center">
      <div class="div__form">
        <h2>Login</h2>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="my-3 d-flex align-items-center flex-column">
            <h3 class="my-0">Username</h3>
            <div class="px-3">{{ form.username }}</div>
          </div>
          <div class="my-3 d-flex align-items-center flex-column">
            <h3 class="my-0">Password</h3>
            <div class="px-3">{{ form.password }}</div>
          </div>
          <button type="submit" class="btn btn-outline-warning">Login</button>
          <a type="submit" href="{% url 'registrationlogin:register' %}" class="btn btn-outline-danger text-danger">Register</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

storyabout/registrationlogin/templates/registrationlogin/registration.html
{% extends 'story/layout.html' %}

{% block content %}
  <div class="back__layer">
     <!-- Errors notifications -->
    {% if form.errors %}
      <div class="error-messages">
        <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>
                <strong>{{ field|capfirst }}</strong>: {{ error }}
              </li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}
     <!-- Registration form -->
    <div class="container__form d-flex justify-content-center align-items-center">
      <div class="div__form">
        <h2>Registration</h2>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="my-3 d-flex align-items-center flex-column">
            <h3 class="my-0">Username</h3>
            <div class="px-3">{{ form.username }}</div>
          </div>
          <div class="my-3 d-flex align-items-center flex-column">
            <h3 class="my-0">Email</h3>
            <div class="px-3">{{ form.email }}</div>
          </div>
          <div class="my-3 d-flex align-items-center flex-column">
            <h3 class="my-0">First Name</h3>
            <div class="px-3">{{ form.first_name }}</div>
          </div>
          <div class="my-3 d-flex align-items-center flex-column">
            <h3 class="my-0">Last Name</h3>
            <div class="px-3">{{ form.last_name }}</div>
          </div>
          <div class="my-3 d-flex align-items-center flex-column">
            <h3 class="my-0">Password</h3>
            <div class="px-3">{{ form.password1 }}</div>
          </div>
          <div class="my-3 d-flex align-items-center flex-column">
            <h3 class="my-0">Confirm Password</h3>
            <div class="px-3">{{ form.password2 }}</div>
          </div>
          <button type="submit" class="btn btn-outline-warning">Register</button>
          <a type="submit" href="{% url 'registrationlogin:login' %}" class="btn btn-outline-danger text-danger">Login</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}